export interface CountryCode {
  code: string;
  flag: string;
  name: string;
  country: string;
}

export const ALL_COUNTRY_CODES: CountryCode[] = [
  { code: '+91', flag: '🇮🇳', name: 'India (+91)', country: 'India' },
  { code: '+1', flag: '🇺🇸', name: 'United States (+1)', country: 'United States' },
  { code: '+1', flag: '🇨🇦', name: 'Canada (+1)', country: 'Canada' },
  { code: '+44', flag: '🇬🇧', name: 'United Kingdom (+44)', country: 'United Kingdom' },
  { code: '+971', flag: '🇦🇪', name: 'United Arab Emirates (+971)', country: 'UAE' },
  { code: '+966', flag: '🇸🇦', name: 'Saudi Arabia (+966)', country: 'Saudi Arabia' },
  { code: '+61', flag: '🇦🇺', name: 'Australia (+61)', country: 'Australia' },
  { code: '+65', flag: '🇸🇬', name: 'Singapore (+65)', country: 'Singapore' },
  { code: '+49', flag: '🇩🇪', name: 'Germany (+49)', country: 'Germany' },
  { code: '+33', flag: '🇫🇷', name: 'France (+33)', country: 'France' },
  { code: '+39', flag: '🇮🇹', name: 'Italy (+39)', country: 'Italy' },
  { code: '+34', flag: '🇪🇸', name: 'Spain (+34)', country: 'Spain' },
  { code: '+55', flag: '🇧🇷', name: 'Brazil (+55)', country: 'Brazil' },
  { code: '+52', flag: '🇲🇽', name: 'Mexico (+52)', country: 'Mexico' },
  { code: '+81', flag: '🇯🇵', name: 'Japan (+81)', country: 'Japan' },
  { code: '+82', flag: '🇰🇷', name: 'South Korea (+82)', country: 'South Korea' },
  { code: '+86', flag: '🇨🇳', name: 'China (+86)', country: 'China' },
  { code: '+92', flag: '🇵🇰', name: 'Pakistan (+92)', country: 'Pakistan' },
  { code: '+880', flag: '🇧🇩', name: 'Bangladesh (+880)', country: 'Bangladesh' },
  { code: '+94', flag: '🇱🇱', name: 'Sri Lanka (+94)', country: 'Sri Lanka' },
  { code: '+977', flag: '🇳🇵', name: 'Nepal (+977)', country: 'Nepal' },
  { code: '+63', flag: '🇵🇭', name: 'Philippines (+63)', country: 'Philippines' },
  { code: '+60', flag: '🇲🇾', name: 'Malaysia (+60)', country: 'Malaysia' },
  { code: '+62', flag: '🇮🇩', name: 'Indonesia (+62)', country: 'Indonesia' },
  { code: '+84', flag: '🇻🇳', name: 'Vietnam (+84)', country: 'Vietnam' },
  { code: '+66', flag: '🇹🇭', name: 'Thailand (+66)', country: 'Thailand' },
  { code: '+27', flag: '🇿🇦', name: 'South Africa (+27)', country: 'South Africa' },
  { code: '+234', flag: '🇳🇬', name: 'Nigeria (+234)', country: 'Nigeria' },
  { code: '+20', flag: '🇪🇬', name: 'Egypt (+20)', country: 'Egypt' },
  { code: '+254', flag: '🇰🇪', name: 'Kenya (+254)', country: 'Kenya' },
  { code: '+233', flag: '🇬🇭', name: 'Ghana (+233)', country: 'Ghana' },
  { code: '+64', flag: '🇳🇿', name: 'New Zealand (+64)', country: 'New Zealand' },
  { code: '+7', flag: '🇷🇺', name: 'Russia (+7)', country: 'Russia' },
  { code: '+90', flag: '🇹🇷', name: 'Turkey (+90)', country: 'Turkey' },
  { code: '+31', flag: '🇳🇱', name: 'Netherlands (+31)', country: 'Netherlands' },
  { code: '+46', flag: '🇸🇪', name: 'Sweden (+46)', country: 'Sweden' },
  { code: '+47', flag: '🇳🇴', name: 'Norway (+47)', country: 'Norway' },
  { code: '+45', flag: '🇩🇰', name: 'Denmark (+45)', country: 'Denmark' },
  { code: '+358', flag: '🇫🇮', name: 'Finland (+358)', country: 'Finland' },
  { code: '+41', flag: '🇨🇭', name: 'Switzerland (+41)', country: 'Switzerland' },
  { code: '+43', flag: '🇦🇹', name: 'Austria (+43)', country: 'Austria' },
  { code: '+32', flag: '🇧🇪', name: 'Belgium (+32)', country: 'Belgium' },
  { code: '+48', flag: '🇵🇱', name: 'Poland (+48)', country: 'Poland' },
  { code: '+351', flag: '🇵🇹', name: 'Portugal (+351)', country: 'Portugal' },
  { code: '+30', flag: '🇬🇷', name: 'Greece (+30)', country: 'Greece' },
  { code: '+353', flag: '🇮🇪', name: 'Ireland (+353)', country: 'Ireland' },
  { code: '+54', flag: '🇦🇷', name: 'Argentina (+54)', country: 'Argentina' },
  { code: '+57', flag: '🇨🇴', name: 'Colombia (+57)', country: 'Colombia' },
  { code: '+56', flag: '🇨🇱', name: 'Chile (+56)', country: 'Chile' },
  { code: '+51', flag: '🇵🇪', name: 'Peru (+51)', country: 'Peru' },
  { code: '+974', flag: '🇶🇦', name: 'Qatar (+974)', country: 'Qatar' },
  { code: '+965', flag: '🇰🇼', name: 'Kuwait (+965)', country: 'Kuwait' },
  { code: '+973', flag: '🇧🇭', name: 'Bahrain (+973)', country: 'Bahrain' },
  { code: '+968', flag: '🇴🇲', name: 'Oman (+968)', country: 'Oman' },
  { code: '+962', flag: '🇯🇴', name: 'Jordan (+962)', country: 'Jordan' },
  { code: '+961', flag: '🇱🇧', name: 'Lebanon (+961)', country: 'Lebanon' },
  { code: '+964', flag: '🇮🇶', name: 'Iraq (+964)', country: 'Iraq' },
  { code: '+98', flag: '🇮🇷', name: 'Iran (+98)', country: 'Iran' },
  { code: '+972', flag: '🇮🇱', name: 'Israel (+972)', country: 'Israel' },
  { code: '+212', flag: '🇲🇦', name: 'Morocco (+212)', country: 'Morocco' },
  { code: '+216', flag: '🇹🇳', name: 'Tunisia (+216)', country: 'Tunisia' },
  { code: '+213', flag: '🇩🇿', name: 'Algeria (+213)', country: 'Algeria' },
  { code: '+380', flag: '🇺🇦', name: 'Ukraine (+380)', country: 'Ukraine' },
  { code: '+420', flag: '🇨🇿', name: 'Czech Republic (+420)', country: 'Czech Republic' },
  { code: '+36', flag: '🇭🇺', name: 'Hungary (+36)', country: 'Hungary' },
  { code: '+40', flag: '🇷🇴', name: 'Romania (+40)', country: 'Romania' },
  { code: '+359', flag: '🇧🇬', name: 'Bulgaria (+359)', country: 'Bulgaria' },
  { code: '+385', flag: '🇭🇷', name: 'Croatia (+385)', country: 'Croatia' },
  { code: '+381', flag: '🇷🇸', name: 'Serbia (+381)', country: 'Serbia' },
  { code: '+421', flag: '🇸🇰', name: 'Slovakia (+421)', country: 'Slovakia' },
  { code: '+386', flag: '🇸🇮', name: 'Slovenia (+386)', country: 'Slovenia' },
  { code: '+356', flag: '🇲🇹', name: 'Malta (+356)', country: 'Malta' },
  { code: '+357', flag: '🇨🇾', name: 'Cyprus (+357)', country: 'Cyprus' },
  { code: '+354', flag: '🇮🇸', name: 'Iceland (+354)', country: 'Iceland' },
  { code: '+352', flag: '🇱🇺', name: 'Luxembourg (+352)', country: 'Luxembourg' },
];
