export const ROUTES = {
  SPLASH: 'SPLASH',
  LOGIN: 'LOGIN',
  REGISTER: 'REGISTER',
  OTP_VERIFICATION: 'OTP_VERIFICATION',
  HOME: 'HOME',
  PROFILE: 'PROFILE',
  MY_PROFILE: 'MY_PROFILE',
  MY_ORDERS: 'MY_ORDERS',
  ORDER_DETAILS: 'ORDER_DETAILS',
  DOCUMENTS: 'DOCUMENTS',
  HELP_SUPPORT: 'HELP_SUPPORT',
  EARNINGS: 'EARNINGS',
} as const;

export type RouteNames = typeof ROUTES[keyof typeof ROUTES];
